Bug fix for nicolargo/glances#1287.

Replace the file `/usr/lib/python2.7/site-packages/glances/plugins/glances_docker.py` with this one.